### PR TITLE
Add NRPE command to monitor /srv/backup-cdn-logs

### PR DESCRIPTION
**Pull request by mattbostock**
__Story: https://trello.com/c/xbsYTau0/33-back-up-processed-cdn-logs__

I'm about to add a corresponding Icinga check for this disk.

### CODE REVIEW

**Comment by alexmuller** [comment]
Can we replace this with an NRPE command which takes an argument so that we don't have to add a new one for each disk?

**Comment by mattbostock** [comment]
@alexmuller This is actually preferable IMHO, as otherwise we'd have to enable [`dont_blame_nrpe`](https://github.com/pdxcat/puppet-module-nrpe/blob/a08aaf73a33b96f5ddd90eafdc20433cfdc323c1/templates/nrpe.cfg.erb#L100) on these boxen, which is a serious security risk.

**Comment by deanwilson** [comment]
I agree with @mattbostock 

IMHO merge when ready but @alexmuller might need convincing.

**Comment by alexmuller** [comment]
I'm happy if you two are :+1:

**Pull request merged**
